### ISSUE TITLE
Support opting out sentry error reporting

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#203]
We think we shouldn't report to sentry without explicit consent from the users.

**Comment by candida-d** [comment]
This can be implemented as a tick-box as part of the onboarding flow though the flow might need some tweaking.

**Comment by campbellssource** [comment]
![00-first-use](https://user-images.githubusercontent.com/13255539/176691618-bf75ab4e-286b-4b1e-bc19-cfc2aa398afb.png)
[Figma](https://www.figma.com/file/W8SV56AAtXpRoQJDQW9ZYt/Vega-Wallet?node-id=1697%3A84645)
Suggest having a modal pop up the first time the user runs the wallet from this version onwards so that wallet that have already been sending sentry events have a prompt to opt out.
This is why this appears first in the flow as it isn't strictly something that happens only as part of sing up.

Note: the language and UI here is the same as that used in the app settings area https://github.com/vegaprotocol/vegawallet-desktop/issues/209
