### ISSUE TITLE
Show Asset Balances

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegawallet-desktop#238]
As a user I want to see asset balances in my wallet.

Tasks:
- [x] Set up apollo client
- [x] Connect to one of the nodes in network configuration
- [x] Query and display balances for given key

**Comment by campbellssource** [comment]
![Image](https://user-images.githubusercontent.com/13255539/175966936-88167937-501f-4b6e-897b-cc2a3c63c8a0.png)

This is a mock up from the [Wallet app wireframes in Figma](https://www.figma.com/file/W8SV56AAtXpRoQJDQW9ZYt/Vega-Wallet?node-id=1317%3A18325).
There are a few things in these designs that either don't exist yet or won't as a result of doing this ticket so here are some notes.

**Where should balances go?**
Balances exist on a specific key, the only other key specific action that has been implemented is sign message.
The existing app is structures about like this
`/Wallets/`
`/Wallets/SignForK-eyxyz/`
I suggest moving to a structure a little more like
`/Wallet/`
`/wallet/key/` <- This would default to showing 👇  
`/wallet/key/balances` 
`/wallet/key/sign` 

![Image](https://user-images.githubusercontent.com/13255539/175966802-942cc4d1-8de4-45cb-9191-f820e8041ff7.png)

You'll see in the design there is a collapsed summary of balances in the Wallet key list. and an expanded one when you have selected a key. It is more important to get the selected key one implemented first. The one in the list of keys is mostly for use cases where you might want to check the balances without changing keys. in the first iteration, the summary of assets on the "select key" (icons X assets) list is less important.

- You'll see the Wallets side bar only shows one wallet. I recommend doing this as part of this work but worth a meeting with design as you pick up this ticket.

- the desktop 2 column layout it not intended for this ticket.

- The transaction page is not for this ticket.
- The balances page in the mock up also includes positions. This is because the headline balance to show for each asset is the sum of balances of all accounts of that asset. e.g. Available + margin accounts + liquidity bonds. Showing just the total doesn't help the user know how much they can withdraw and showing only your available balances would be misleading. Therefore the design lists all sub accounts but has a specific component to show margin accounts liquidity accounts, and a standard key/value for available. In this design there is a spark line for that market price as well as a count of your position and open order size. In a first iteration these can be left out and instead show `Margin: [market code]` `[balance]` or `liquidity;` `[market code]` e.g. **Margin: BTC/USD Mar**.
- There is also a visualisation for each asset that can be left out of the first iteration, it attempts to show how your collateral is distributed and warn when you are close to a margin call.
- As well as listing collateral balances there is a row for the amount of VEGA you have associated (or in the future "locked for staking". In the first iteration it can just should the amount associated (seen at `Party.stake.currentStakeAvailable`). Future iterations can then list the detail on how this associated stake has been delegated to Validators.
- You'll see an "all keys" item in the designs (there when there is more than one key) this is intended to show a sum of all balance across all keys. It is not required for this ticket.
