### ISSUE TITLE
Retrieve default vegaHome

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#275]
** Resolve with #297 **

To set a default vegaHome you pass an empty string. This is fine but when retrieving the app config it would be useful if we could actually get the path of the default vega home for the current OS. Either in the vegaHome field or a new field.

**Comment by gordsport** [comment]
Hey @mattrussell36 
Is this issue a must have on the backend for before trading is enabled?

**Comment by ValentinTrinque** [comment]
Because we are using the XDG standard, that is not as straight forward at it seems. We we specify a custom vega home, everything is under the same directory, however, when using the default home location, the files are living under different directory on the file system based on their nature.

Log files are stored in a different place as the config.

So if we are to address this we will have enhance the backend API to return something more representative.

**Comment by mattrussell36** [comment]
Okay. @gordsport this was more of a nice to have lets consider it descoped

**Comment by ckpringle** [comment]
Combine with the log file ticket
